name: Docker Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Docker version
        run: docker version

      - name: List Docker project files
        run: ls -la projects/my-nginx-image

      - name: Build Docker image
        run: docker build -t my-nginx-image ./projects/my-nginx-image
