name: Environment Variables Pipeline

on:
  push:
    branches:
      - main

env:
  APP_ENV: dev
  APP_NAME: devops-learning

jobs:
  show-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show application environment
        run: |
          echo "Application name: $APP_NAME"
          echo "Environment: $APP_ENV"

      - name: Show repository files
        run: ls -la
