name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/my-nginx-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show image name
        run: |
          echo "Registry: $REGISTRY"
          echo "Image name: $IMAGE_NAME"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Full image tag: $REGISTRY/${IMAGE_NAME,,}:$GITHUB_SHA"

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $REGISTRY/${IMAGE_NAME,,}:$GITHUB_SHA ./projects/my-nginx-image

      - name: Push Docker image
        run: docker push $REGISTRY/${IMAGE_NAME,,}:$GITHUB_SHA
